from __future__ import annotations

from django.urls import path

from .views import (
    BuyerCreateView,
    BuyerDeleteView,
    BuyerDetailView,
    BuyerListView,
    BuyerUpdateView,
    CarCreateView,
    CarDeleteView,
    CarDetailView,
    CarListView,
    CarUpdateView,
    ColorCreateView,
    ColorDeleteView,
    ColorDetailView,
    ColorListView,
    ColorUpdateView,
    CountryCreateView,
    CountryDeleteView,
    CountryDetailView,
    CountryListView,
    CountryUpdateView,
    FirmCreateView,
    FirmDeleteView,
    FirmDetailView,
    FirmListView,
    FirmUpdateView,
    HomeView,
    ProductCreateView,
    ProductDeleteView,
    ProductDetailView,
    ProductListView,
    ProductUpdateView,
    SaleActCreateView,
    SaleActDeleteView,
    SaleActDetailView,
    SaleActListView,
    SaleActUpdateView,
    SellerCreateView,
    SellerDeleteView,
    SellerDetailView,
    SellerListView,
    SellerUpdateView,
)

app_name = "dealership"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("countries/", CountryListView.as_view(), name="country-list"),
    path("countries/create/", CountryCreateView.as_view(), name="country-create"),
    path("countries/<int:pk>/", CountryDetailView.as_view(), name="country-detail"),
    path(
        "countries/<int:pk>/update/",
        CountryUpdateView.as_view(),
        name="country-update",
    ),
    path(
        "countries/<int:pk>/delete/",
        CountryDeleteView.as_view(),
        name="country-delete",
    ),
    path("colors/", ColorListView.as_view(), name="color-list"),
    path("colors/create/", ColorCreateView.as_view(), name="color-create"),
    path("colors/<int:pk>/", ColorDetailView.as_view(), name="color-detail"),
    path("colors/<int:pk>/update/", ColorUpdateView.as_view(), name="color-update"),
    path("colors/<int:pk>/delete/", ColorDeleteView.as_view(), name="color-delete"),
    path("firms/", FirmListView.as_view(), name="firm-list"),
    path("firms/create/", FirmCreateView.as_view(), name="firm-create"),
    path("firms/<int:pk>/", FirmDetailView.as_view(), name="firm-detail"),
    path("firms/<int:pk>/update/", FirmUpdateView.as_view(), name="firm-update"),
    path("firms/<int:pk>/delete/", FirmDeleteView.as_view(), name="firm-delete"),
    path("sellers/", SellerListView.as_view(), name="seller-list"),
    path("sellers/create/", SellerCreateView.as_view(), name="seller-create"),
    path("sellers/<int:pk>/", SellerDetailView.as_view(), name="seller-detail"),
    path("sellers/<int:pk>/update/", SellerUpdateView.as_view(), name="seller-update"),
    path("sellers/<int:pk>/delete/", SellerDeleteView.as_view(), name="seller-delete"),
    path("buyers/", BuyerListView.as_view(), name="buyer-list"),
    path("buyers/create/", BuyerCreateView.as_view(), name="buyer-create"),
    path("buyers/<int:pk>/", BuyerDetailView.as_view(), name="buyer-detail"),
    path("buyers/<int:pk>/update/", BuyerUpdateView.as_view(), name="buyer-update"),
    path("buyers/<int:pk>/delete/", BuyerDeleteView.as_view(), name="buyer-delete"),
    path("cars/", CarListView.as_view(), name="car-list"),
    path("cars/create/", CarCreateView.as_view(), name="car-create"),
    path("cars/<int:pk>/", CarDetailView.as_view(), name="car-detail"),
    path("cars/<int:pk>/update/", CarUpdateView.as_view(), name="car-update"),
    path("cars/<int:pk>/delete/", CarDeleteView.as_view(), name="car-delete"),
    path("products/", ProductListView.as_view(), name="product-list"),
    path("products/create/", ProductCreateView.as_view(), name="product-create"),
    path("products/<int:pk>/", ProductDetailView.as_view(), name="product-detail"),
    path("products/<int:pk>/update/", ProductUpdateView.as_view(), name="product-update"),
    path("products/<int:pk>/delete/", ProductDeleteView.as_view(), name="product-delete"),
    path("sales/", SaleActListView.as_view(), name="sale-act-list"),
    path("sales/create/", SaleActCreateView.as_view(), name="sale-act-create"),
    path("sales/<int:pk>/", SaleActDetailView.as_view(), name="sale-act-detail"),
    path("sales/<int:pk>/update/", SaleActUpdateView.as_view(), name="sale-act-update"),
    path("sales/<int:pk>/delete/", SaleActDeleteView.as_view(), name="sale-act-delete"),
]
