# Generated by Django 6.0.6 on 2026-06-17 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя покупателя')),
            ],
            options={
                'verbose_name': 'Покупатель',
                'verbose_name_plural': 'Покупатели',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название цвета')),
                ('hex', models.CharField(max_length=7, verbose_name='HEX-код')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название страны')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя продавца')),
            ],
            options={
                'verbose_name': 'Продавец',
                'verbose_name_plural': 'Продавцы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название фирмы')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='firms', to='dealership.country', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Фирма',
                'verbose_name_plural': 'Фирмы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255, verbose_name='Модель')),
                ('engine_power', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Мощность двигателя')),
                ('length', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Длина')),
                ('width', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Ширина')),
                ('release_year', models.PositiveIntegerField(verbose_name='Год выпуска')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='dealership.color', verbose_name='Цвет')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='dealership.country', verbose_name='Страна')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='dealership.firm', verbose_name='Фирма')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
                'ordering': ['model', 'release_year'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Цена')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='dealership.car', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-price', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SaleAct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_at', models.DateTimeField(verbose_name='Дата и время покупки')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_acts', to='dealership.buyer', verbose_name='Покупатель')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_acts', to='dealership.product', verbose_name='Товар')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_acts', to='dealership.seller', verbose_name='Продавец')),
            ],
            options={
                'verbose_name': 'Акт продажи',
                'verbose_name_plural': 'Акты продажи',
                'ordering': ['-buy_at'],
            },
        ),
    ]
